import SwiftUI
import SpecRuntime

@Observable
final class ReactivityPerfViewModel {
  var input: Any = ""
  var upper: Any { (input as? String ?? "").uppercased() }
  var lower: Any { (input as? String ?? "").lowercased() }
  var len: Any { specAdd(specLength(input), "") }
  var reversed: Any { (((input as? String ?? "").components(separatedBy: "" as? String ?? "") as? [Any] ?? []).reversed().map { $0 } as? [Any] ?? []).map { String(describing: $0) }.joined(separator: "" as? String ?? "") }
  var trimmed: Any { (input as? String ?? "").trimmingCharacters(in: .whitespaces) }
  var first5: Any { specSlice(input, 0, 5) }
  var last5: Any { specSlice(input, -5) }
  var words: Any { specAdd(specLength((input as? String ?? "").components(separatedBy: " " as? String ?? "")), " words") }
  var chars: Any { specAdd(specLength(input), " chars") }
  func dispatch(_ event: Any, _ payload: Any? = nil) {}
}

struct ReactivityPerfView: View {
  @State private var vm = ReactivityPerfViewModel()
  var body: some View {
    VStack() {
      VStack(spacing: CGFloat(16)) {
        Text(verbatim: specString("Reactivity Performance Test"))
          .font(.title2.bold())
          .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
        Text(verbatim: specString("Type below — all outputs are bound to the same state signal."))
          .font(.callout.bold())
          .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
        VStack(spacing: CGFloat(8)) {
          Text(verbatim: specString("Input"))
            .font(.body.bold())
            .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
          TextField("", text: Binding(get: { vm.input as? String ?? "" }, set: { vm.input = $0 }))
            .textFieldStyle(.roundedBorder)
        }
        .padding(CGFloat(12))
        .background(ThemeManager.shared.color("semantic.background"), in: RoundedRectangle(cornerRadius: ThemeManager.shared.radius("md")))
        HStack(alignment: .center, spacing: CGFloat(12)) {
          VStack() {
            Text(verbatim: specString(vm.chars))
              .font(.body.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.accent"))
          }
          .padding(CGFloat(8))
          .background(ThemeManager.shared.color("semantic.background"), in: RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
          VStack() {
            Text(verbatim: specString(vm.words))
              .font(.body.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.accent"))
          }
          .padding(CGFloat(8))
          .background(ThemeManager.shared.color("semantic.background"), in: RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
        }

        VStack(spacing: CGFloat(8)) {
          Text(verbatim: specString("Computed Derivations"))
            .font(.headline.bold())
            .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
          HStack(alignment: .center, spacing: CGFloat(8)) {
            Text(verbatim: specString("UPPER:"))
              .font(.body.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(vm.upper))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
          }

          HStack(alignment: .center, spacing: CGFloat(8)) {
            Text(verbatim: specString("lower:"))
              .font(.body.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(vm.lower))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
          }

          HStack(alignment: .center, spacing: CGFloat(8)) {
            Text(verbatim: specString("Reversed:"))
              .font(.body.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(vm.reversed))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
          }

          HStack(alignment: .center, spacing: CGFloat(8)) {
            Text(verbatim: specString("Trimmed:"))
              .font(.body.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(vm.trimmed))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
          }

          HStack(alignment: .center, spacing: CGFloat(8)) {
            Text(verbatim: specString("First 5:"))
              .font(.body.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(vm.first5))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
          }

          HStack(alignment: .center, spacing: CGFloat(8)) {
            Text(verbatim: specString("Last 5:"))
              .font(.body.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(vm.last5))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
          }

        }
        .padding(CGFloat(12))
        .background(ThemeManager.shared.color("semantic.background"), in: RoundedRectangle(cornerRadius: ThemeManager.shared.radius("md")))
        VStack(spacing: CGFloat(8)) {
          Text(verbatim: specString("50 Direct Bindings"))
            .font(.headline.bold())
            .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
          LazyVGrid(columns: Array(repeating: GridItem(.flexible()), count: 5), spacing: CGFloat(4)) {
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
            Text(verbatim: specString(vm.input))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
          }

        }
        .padding(CGFloat(12))
        .background(ThemeManager.shared.color("semantic.background"), in: RoundedRectangle(cornerRadius: ThemeManager.shared.radius("md")))
        VStack(spacing: CGFloat(8)) {
          Text(verbatim: specString("50 Computed Bindings (template strings)"))
            .font(.headline.bold())
            .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
          LazyVGrid(columns: Array(repeating: GridItem(.flexible()), count: 5), spacing: CGFloat(4)) {
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
            Text(verbatim: specString(">\(specString(vm.input))<"))
              .font(.callout.bold())
              .foregroundStyle(ThemeManager.shared.color("semantic.text-secondary"))
          }

        }
        .padding(CGFloat(12))
        .background(ThemeManager.shared.color("semantic.background"), in: RoundedRectangle(cornerRadius: ThemeManager.shared.radius("md")))
        VStack(spacing: CGFloat(8)) {
          Text(verbatim: specString("20 Styled Text Mirrors"))
            .font(.headline.bold())
            .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
          LazyVGrid(columns: Array(repeating: GridItem(.flexible()), count: 4), spacing: CGFloat(4)) {
            VStack() {
              Text(verbatim: specString(vm.input))
                .font(.callout.bold())
            }
            .padding(CGFloat(4))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            VStack() {
              Text(verbatim: specString(vm.input))
                .font(.callout.bold())
            }
            .padding(CGFloat(4))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            VStack() {
              Text(verbatim: specString(vm.input))
                .font(.callout.bold())
            }
            .padding(CGFloat(4))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            VStack() {
              Text(verbatim: specString(vm.input))
                .font(.callout.bold())
            }
            .padding(CGFloat(4))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            VStack() {
              Text(verbatim: specString(vm.input))
                .font(.callout.bold())
            }
            .padding(CGFloat(4))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            VStack() {
              Text(verbatim: specString(vm.input))
                .font(.callout.bold())
            }
            .padding(CGFloat(4))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            VStack() {
              Text(verbatim: specString(vm.input))
                .font(.callout.bold())
            }
            .padding(CGFloat(4))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            VStack() {
              Text(verbatim: specString(vm.input))
                .font(.callout.bold())
            }
            .padding(CGFloat(4))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            VStack() {
              Text(verbatim: specString(vm.input))
                .font(.callout.bold())
            }
            .padding(CGFloat(4))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            VStack() {
              Text(verbatim: specString(vm.input))
                .font(.callout.bold())
            }
            .padding(CGFloat(4))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            VStack() {
              Text(verbatim: specString(vm.input))
                .font(.callout.bold())
            }
            .padding(CGFloat(4))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            VStack() {
              Text(verbatim: specString(vm.input))
                .font(.callout.bold())
            }
            .padding(CGFloat(4))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            VStack() {
              Text(verbatim: specString(vm.input))
                .font(.callout.bold())
            }
            .padding(CGFloat(4))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            VStack() {
              Text(verbatim: specString(vm.input))
                .font(.callout.bold())
            }
            .padding(CGFloat(4))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            VStack() {
              Text(verbatim: specString(vm.input))
                .font(.callout.bold())
            }
            .padding(CGFloat(4))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            VStack() {
              Text(verbatim: specString(vm.input))
                .font(.callout.bold())
            }
            .padding(CGFloat(4))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            VStack() {
              Text(verbatim: specString(vm.input))
                .font(.callout.bold())
            }
            .padding(CGFloat(4))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            VStack() {
              Text(verbatim: specString(vm.input))
                .font(.callout.bold())
            }
            .padding(CGFloat(4))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            VStack() {
              Text(verbatim: specString(vm.input))
                .font(.callout.bold())
            }
            .padding(CGFloat(4))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            VStack() {
              Text(verbatim: specString(vm.input))
                .font(.callout.bold())
            }
            .padding(CGFloat(4))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
            .clipShape(RoundedRectangle(cornerRadius: ThemeManager.shared.radius("sm")))
          }

        }
        .padding(CGFloat(12))
        .background(ThemeManager.shared.color("semantic.background"), in: RoundedRectangle(cornerRadius: ThemeManager.shared.radius("md")))
      }
      .padding(CGFloat(20))
    }
    .foregroundStyle(ThemeManager.shared.color("semantic.text-primary"))
    .environment(\.font, ThemeManager.shared.themeFont())
    .fontDesign(ThemeManager.shared.fontDesign())
  }
}
