import SwiftUI

// Auto-generated navigation shell from App surface sidebar definition.
// Do not edit — regenerated by `spec build --target ios`.

// MARK: - Navigation Model

enum NavDestination: String, CaseIterable, Identifiable {
  case dashboard, analytics
  case detail, create, wizard
  case datagrid, editgrid, categories
  case team
  case activity, notifications
  case perfgrid, perfsignals, reactivityperf
  case landing2
  case themepreview
  case charts, drag, formdemo, routing, mobiledemo
  case featuretest
  case settings

  var id: String { rawValue }

  var title: String {
    switch self {
    case .dashboard: return "Dashboard"
    case .analytics: return "Analytics"
    case .detail: return "Task Detail"
    case .create: return "Create Task"
    case .wizard: return "Task Wizard"
    case .datagrid: return "Product Catalog"
    case .editgrid: return "Editable Grid"
    case .categories: return "Categories"
    case .team: return "Team"
    case .activity: return "Activity"
    case .notifications: return "Notifications"
    case .perfgrid: return "Grid 10K"
    case .perfsignals: return "Signal Test"
    case .reactivityperf: return "Reactivity Perf"
    case .landing2: return "Landing Page"
    case .themepreview: return "Theme Preview"
    case .charts: return "Charts"
    case .drag: return "Drag & Drop"
    case .formdemo: return "Form Validation"
    case .routing: return "Routing"
    case .mobiledemo: return "Mobile Demo"
    case .featuretest: return "Feature Test (P1-P8)"
    case .settings: return "Settings"
    }
  }

  var icon: String {
    switch self {
    case .dashboard: return "house.fill"
    case .analytics: return "chart.bar.fill"
    case .detail: return "eye.fill"
    case .create: return "plus.circle.fill"
    case .wizard: return "list.bullet.clipboard.fill"
    case .datagrid: return "tablecells.fill"
    case .editgrid: return "pencil.and.list.clipboard"
    case .categories: return "list.bullet.clipboard.fill"
    case .team: return "person.2.fill"
    case .activity: return "clock.fill"
    case .notifications: return "bell.fill"
    case .perfgrid: return "bolt.fill"
    case .perfsignals: return "waveform.path.ecg"
    case .reactivityperf: return "bolt.fill"
    case .landing2: return "arrow.triangle.branch"
    case .themepreview: return "paintpalette.fill"
    case .charts: return "chart.bar.fill"
    case .drag: return "tablecells.fill"
    case .formdemo: return "pencil.and.list.clipboard"
    case .routing: return "arrow.triangle.branch"
    case .mobiledemo: return "iphone"
    case .featuretest: return "checkmark.seal.fill"
    case .settings: return "gearshape.fill"
    }
  }

  static var sections: [(heading: String, items: [NavDestination])] {
    [
      ("Overview", [.dashboard, .analytics]),
      ("Tasks", [.detail, .create, .wizard]),
      ("Data", [.datagrid, .editgrid, .categories]),
      ("People", [.team]),
      ("Monitoring", [.activity, .notifications]),
      ("Performance", [.perfgrid, .perfsignals, .reactivityperf]),
      ("Marketing", [.landing2]),
      ("Design", [.themepreview]),
      ("Components", [.charts, .drag, .formdemo, .routing, .mobiledemo]),
      ("Testing", [.featuretest]),
      ("System", [.settings]),
    ]
  }
}

// MARK: - Content View

struct ContentDestinationView: View {
  let destination: NavDestination
  @State private var showThemeDrawer = false

  var body: some View {
    ScrollView {
      destinationContent
        .padding(.horizontal)
        .padding(.bottom, 20)
    }
    .navigationTitle(destination.title)
    .navigationBarTitleDisplayMode(.large)
    .toolbar {
      ToolbarItem(placement: .topBarTrailing) {
        Button {
          showThemeDrawer = true
        } label: {
          Image(systemName: "paintpalette")
        }
      }
    }
    .sheet(isPresented: $showThemeDrawer) {
      NavigationStack {
        ScrollView {
          SpecThemePickerView()
            .padding()
        }
        .navigationTitle("Theme")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar {
          ToolbarItem(placement: .topBarTrailing) {
            Button("Done") { showThemeDrawer = false }
          }
        }
      }
      .presentationDetents([.medium, .large])
    }
  }

  @ViewBuilder
  private var destinationContent: some View {
    switch destination {
    case .dashboard: VStack(spacing: 20) {
        StatsBarView()
        TaskTableView()
      }
    case .analytics: AnalyticsViewView()
    case .detail: TaskTableView()
    case .create: TaskFormView()
    case .wizard: TaskWizardView()
    case .datagrid: DataGridDemoView()
    case .editgrid: DataGridDemoView()
    case .categories: TreeDemoView()
    case .team: TeamDirectoryView()
    case .activity: ActivityFeedView()
    case .notifications: NotificationsPanelView()
    case .perfgrid: DataGridDemoView()
    case .perfsignals: FeatureTestView()
    case .reactivityperf: PerfGridView()
    case .landing2: ThemePreviewView() // placeholder
    case .themepreview: ThemeBuilderView()
    case .charts: ChartDemoView()
    case .drag: DragDemoView()
    case .formdemo: TaskFormView()
    case .routing: RoutingDemoView()
    case .mobiledemo: DataGridDemoView()
    case .featuretest: FeatureTestView()
    case .settings: SettingsPanelView()
    }
  }
}

// MARK: - Sidebar

struct SidebarListView: View {
  @Binding var selection: NavDestination?

  var body: some View {
    List(selection: $selection) {
      ForEach(NavDestination.sections, id: \.heading) { section in
        Section(section.heading) {
          ForEach(section.items) { item in
            Label(item.title, systemImage: item.icon).tag(item)
          }
        }
      }
    }
    .navigationTitle("Spectest")
  }
}

// MARK: - Tab Items

enum TabItem: String, CaseIterable {
  case dashboard, team, activity, notifications, more

  var destination: NavDestination? {
    switch self {
    case .dashboard: return .dashboard
    case .team: return .team
    case .activity: return .activity
    case .notifications: return .notifications
    case .more: return nil
    }
  }

  var title: String {
    switch self {
    case .dashboard: return "Dashboard"
    case .team: return "Team"
    case .activity: return "Activity"
    case .notifications: return "Notifications"
    case .more: return "More"
    }
  }

  var icon: String {
    switch self {
    case .dashboard: return "house.fill"
    case .team: return "person.2.fill"
    case .activity: return "clock.fill"
    case .notifications: return "bell.fill"
    case .more: return "ellipsis.circle.fill"
    }
  }
}

// MARK: - More Destinations

private let moreDestinations: [NavDestination] = [
  .analytics,
  .detail,
  .create,
  .wizard,
  .datagrid,
  .editgrid,
  .categories,
  .perfgrid,
  .perfsignals,
  .reactivityperf,
  .landing2,
  .themepreview,
  .charts,
  .drag,
  .formdemo,
  .routing,
  .mobiledemo,
  .featuretest,
  .settings,
]

// MARK: - Adaptive Root

struct AdaptiveRootView: View {
  @Environment(\.horizontalSizeClass) private var sizeClass
  @State private var sidebarSelection: NavDestination? = .dashboard
  @State private var selectedTab: TabItem = .dashboard

  var body: some View {
    if sizeClass == .regular {
      NavigationSplitView {
        SidebarListView(selection: $sidebarSelection)
      } detail: {
        if let dest = sidebarSelection {
          ContentDestinationView(destination: dest)
        } else {
          ContentUnavailableView("Select a page", systemImage: "sidebar.left", description: Text("Choose from the sidebar"))
        }
      }
    } else {
      TabView(selection: $selectedTab) {
        ForEach(TabItem.allCases, id: \.self) { tab in
          Group {
            if tab == .more {
              NavigationStack {
                List {
                  ForEach(moreDestinations) { dest in
                    NavigationLink(value: dest) {
                      Label(dest.title, systemImage: dest.icon)
                    }
                  }
                }
                .navigationTitle("More")
                .navigationDestination(for: NavDestination.self) { dest in
                  ContentDestinationView(destination: dest)
                }
              }
            } else if let dest = tab.destination {
              NavigationStack {
                ContentDestinationView(destination: dest)
              }
            }
          }
          .tabItem {
            Label(tab.title, systemImage: tab.icon)
          }
          .tag(tab)
        }
      }
    }
  }
}

// MARK: - App Entry Point

@main
struct SpectestApp: App {
  init() {
    SpecThemeRegistry.registerAll()
    SpecThemeRegistry.loadSavedTheme()
  }

  var body: some Scene {
    WindowGroup {
      AdaptiveRootView()
        .preferredColorScheme(.light) // Theme tokens are light-mode hex; force light until dark-mode variants land
    }
  }
}
