import { bindCollection, bindStyle, bindText, bindVisibility, computed, createSignal, createSource, scheduleWrite, subscribe } from '@spec/runtime';
/* Generated by @spec/compiler from C:\projects\spectest\src\app.spec */
import { mountButton } from '@spec/components/button.js';
import { mountCheckbox } from '@spec/components/checkbox.js';
import { mountDatePicker } from '@spec/components/date-picker.js';
import { mountIcon } from '@spec/components/icon.js';
import { mountImage } from '@spec/components/image.js';
import { mountInput } from '@spec/components/input.js';
import { mountSelect } from '@spec/components/select.js';
import { mountTabs } from '@spec/components/tabs.js';
import { mountToggle } from '@spec/components/toggle.js';

export function mountStatusBadge(container, status) {
  // DOM
  const _root = document.createElement('div');
  _root.style.color = '#202732';
  _root.style.fontFamily = "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif";
  const _el0 = document.createElement('span');
  _el0.style.fontSize = '11.2px';
  _el0.style.fontWeight = '500';
  _el0.style.lineHeight = '1.4';
  const _t0 = document.createTextNode('');
  _t0.data = String((status === "todo" ? "Todo" : (status === "in-progress" ? "In Progress" : (status === "done" ? "Done" : "Unknown"))));
  _el0.appendChild(_t0);
  _root.appendChild(_el0);

  container.appendChild(_root);
  return () => _root.remove();
}

export function mountPriorityBadge(container, priority) {
  // DOM
  const _root = document.createElement('div');
  _root.style.color = '#202732';
  _root.style.fontFamily = "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif";
  const _el0 = document.createElement('span');
  _el0.style.fontSize = '11.2px';
  _el0.style.fontWeight = '500';
  _el0.style.lineHeight = '1.4';
  const _t0 = document.createTextNode('');
  _t0.data = String((priority === "low" ? "Low" : (priority === "medium" ? "Medium" : (priority === "high" ? "High" : (priority === "critical" ? "Critical" : "—")))));
  _el0.appendChild(_t0);
  _root.appendChild(_el0);

  container.appendChild(_root);
  return () => _root.remove();
}

export function mountStatsBar(container, total, done, inProgress, todo) {
  // DOM
  const _root = document.createElement('div');
  _root.style.color = '#202732';
  _root.style.fontFamily = "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif";
  _root.style.display = 'flex';
  _root.style.flexDirection = 'row';
  _root.style.gap = '16px';
  _root.style.alignItems = 'center';
  const _el0 = document.createElement('div');
  _el0.style.padding = '12px';
  _el0.style.backgroundColor = '#eef2ff';
  _el0.style.borderRadius = '8px';
  _el0.style.display = 'flex';
  _el0.style.flexDirection = 'row';
  _el0.style.gap = '8px';
  _el0.style.alignItems = 'center';
  mountIcon(_el0, { name: "list", size: "18px", color: "#6366f1" });
  const _el1 = document.createElement('span');
  _el1.style.fontSize = '14px';
  _el1.style.fontWeight = '500';
  _el1.style.lineHeight = '1.4';
  const _t0 = document.createTextNode('');
  _t0.data = String(`Total: ${total}`);
  _el1.appendChild(_t0);
  _el0.appendChild(_el1);
  _root.appendChild(_el0);
  const _el2 = document.createElement('div');
  _el2.style.padding = '12px';
  _el2.style.backgroundColor = '#ecfdf5';
  _el2.style.borderRadius = '8px';
  _el2.style.display = 'flex';
  _el2.style.flexDirection = 'row';
  _el2.style.gap = '8px';
  _el2.style.alignItems = 'center';
  mountIcon(_el2, { name: "check", size: "18px", color: "#10b981" });
  const _el3 = document.createElement('span');
  _el3.style.fontSize = '14px';
  _el3.style.fontWeight = '500';
  _el3.style.lineHeight = '1.4';
  const _t1 = document.createTextNode('');
  _t1.data = String(`Done: ${done}`);
  _el3.appendChild(_t1);
  _el2.appendChild(_el3);
  _root.appendChild(_el2);
  const _el4 = document.createElement('div');
  _el4.style.padding = '12px';
  _el4.style.backgroundColor = '#fffbeb';
  _el4.style.borderRadius = '8px';
  _el4.style.display = 'flex';
  _el4.style.flexDirection = 'row';
  _el4.style.gap = '8px';
  _el4.style.alignItems = 'center';
  mountIcon(_el4, { name: "loader", size: "18px", color: "#f59e0b" });
  const _el5 = document.createElement('span');
  _el5.style.fontSize = '14px';
  _el5.style.fontWeight = '500';
  _el5.style.lineHeight = '1.4';
  const _t2 = document.createTextNode('');
  _t2.data = String(`In Progress: ${inProgress}`);
  _el5.appendChild(_t2);
  _el4.appendChild(_el5);
  _root.appendChild(_el4);
  const _el6 = document.createElement('div');
  _el6.style.padding = '12px';
  _el6.style.backgroundColor = '#f8fafc';
  _el6.style.borderRadius = '8px';
  _el6.style.display = 'flex';
  _el6.style.flexDirection = 'row';
  _el6.style.gap = '8px';
  _el6.style.alignItems = 'center';
  mountIcon(_el6, { name: "circle", size: "18px", color: "#94a3b8" });
  const _el7 = document.createElement('span');
  _el7.style.fontSize = '14px';
  _el7.style.fontWeight = '500';
  _el7.style.lineHeight = '1.4';
  const _t3 = document.createTextNode('');
  _t3.data = String(`Todo: ${todo}`);
  _el7.appendChild(_t3);
  _el6.appendChild(_el7);
  _root.appendChild(_el6);

  container.appendChild(_root);
  return () => _root.remove();
}

export function mountTaskTable(container) {
  // @state
  const filter = createSignal("all");

  // @source
  const _src_tasks = createTasksAPI();
  const tasks = _src_tasks.data;
  const tasksLoading = _src_tasks.loading;
  const tasksError = _src_tasks.error;
  _src_tasks.fetch();

  // @computed
  const taskList = computed(() => (tasks() != null ? tasks() : []), [tasks]);
  const filteredTasks = computed(() => (filter() == "all" ? taskList() : taskList().filter((t) => t.status == filter())), [filter, taskList]);
  const taskCount = computed(() => `${filteredTasks().length} tasks`, [filteredTasks]);
  const hasNoResults = computed(() => filteredTasks().length == 0, [filteredTasks]);

  // @actions
  function setFilter(f) {
    filter.set(f);
  }

  // DOM
  const _root = document.createElement('div');
  _root.style.color = '#202732';
  _root.style.fontFamily = "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif";
  _root.style.display = 'flex';
  _root.style.flexDirection = 'column';
  _root.style.gap = '16px';
  const _el0 = document.createElement('h3');
  _el0.style.fontSize = '27.3px';
  _el0.style.fontWeight = '600';
  _el0.style.lineHeight = '1.2';
  const _t0 = document.createTextNode('');
  _t0.data = String("Tasks");
  _el0.appendChild(_t0);
  _root.appendChild(_el0);
  const _el1 = document.createElement('div');
  _el1.style.padding = '12px';
  _el1.style.backgroundColor = '#f8fafc';
  _el1.style.borderRadius = '8px';
  _el1.style.display = 'flex';
  _el1.style.flexDirection = 'row';
  _el1.style.gap = '8px';
  _el1.style.alignItems = 'center';
  const _el2 = document.createElement('p');
  _el2.style.fontSize = '11.2px';
  _el2.style.fontWeight = '400';
  _el2.style.lineHeight = '1.5';
  _el2.style.color = '#64748b';
  const _t1 = document.createTextNode('');
  bindText(_t1, taskCount);
  _el2.appendChild(_t1);
  _el1.appendChild(_el2);
  mountButton(_el1, { onClick: () => { setFilter("all"); }, label: "All", variant: "secondary" });
  mountButton(_el1, { onClick: () => { setFilter("todo"); }, label: "Todo", variant: "secondary" });
  mountButton(_el1, { onClick: () => { setFilter("in-progress"); }, label: "In Progress", variant: "secondary" });
  mountButton(_el1, { onClick: () => { setFilter("done"); }, label: "Done", variant: "secondary" });
  _root.appendChild(_el1);
  const _el3 = document.createElement('div');
  _el3.style.padding = '16px';
  _el3.style.backgroundColor = '#f0f9ff';
  _el3.style.borderRadius = '8px';
  bindVisibility(_el3, tasksLoading);
  const _el4 = document.createElement('p');
  _el4.style.fontSize = '11.2px';
  _el4.style.fontWeight = '400';
  _el4.style.lineHeight = '1.5';
  _el4.style.color = '#64748b';
  const _t2 = document.createTextNode('');
  _t2.data = String("Loading tasks...");
  _el4.appendChild(_t2);
  _el3.appendChild(_el4);
  _root.appendChild(_el3);
  const _el5 = document.createElement('div');
  _el5.style.padding = '12px';
  _el5.style.backgroundColor = '#fef2f2';
  _el5.style.border = '1px solid #fecaca';
  _el5.style.borderRadius = '8px';
  bindVisibility(_el5, tasksError);
  const _el6 = document.createElement('p');
  _el6.style.fontSize = '11.2px';
  _el6.style.fontWeight = '400';
  _el6.style.lineHeight = '1.5';
  _el6.style.color = 'red';
  const _t3 = document.createTextNode('');
  _t3.data = String("Failed to load tasks.");
  _el6.appendChild(_t3);
  _el5.appendChild(_el6);
  _root.appendChild(_el5);
  const _list0 = document.createElement('div');
  bindCollection(_list0, filteredTasks, (task, index) => {
    const _item = document.createElement('div');
    const _el7 = document.createElement('div');
    _el7.style.padding = '12px';
    _el7.style.backgroundColor = '#ffffff';
    _el7.style.border = '1px solid #e2e8f0';
    _el7.style.borderRadius = '8px';
    _el7.style.display = 'flex';
    _el7.style.flexDirection = 'row';
    _el7.style.gap = '16px';
    _el7.style.alignItems = 'center';
    const _el8 = document.createElement('span');
    _el8.style.fontSize = '11.2px';
    _el8.style.fontWeight = '400';
    _el8.style.lineHeight = '1.5';
    _el8.style.fontFamily = "'Menlo', 'Consolas', monospace";
    _el8.style.color = '#94a3b8';
    const _t4 = document.createTextNode('');
    _t4.data = String(`${index}`);
    _el8.appendChild(_t4);
    _el7.appendChild(_el8);
    const _el9 = document.createElement('div');
    _el9.style.display = 'flex';
    _el9.style.flexDirection = 'column';
    _el9.style.gap = '4px';
    const _el10 = document.createElement('p');
    _el10.style.fontSize = '14px';
    _el10.style.fontWeight = '400';
    _el10.style.lineHeight = '1.5';
    _el10.style.fontWeight = '500';
    const _t5 = document.createTextNode('');
    _t5.data = String(task.title);
    _el10.appendChild(_t5);
    _el9.appendChild(_el10);
    const _el11 = document.createElement('p');
    _el11.style.fontSize = '11.2px';
    _el11.style.fontWeight = '400';
    _el11.style.lineHeight = '1.5';
    _el11.style.color = '#64748b';
    const _t6 = document.createTextNode('');
    _t6.data = String(task.assignee);
    _el11.appendChild(_t6);
    _el9.appendChild(_el11);
    _el7.appendChild(_el9);
    mountStatusBadge(_el7, task.status);
    mountPriorityBadge(_el7, task.priority);
    _item.appendChild(_el7);
    return _item;
  });
  _root.appendChild(_list0);
  const _el12 = document.createElement('div');
  _el12.style.padding = '16px';
  _el12.style.backgroundColor = '#f8fafc';
  _el12.style.borderRadius = '8px';
  bindVisibility(_el12, hasNoResults);
  const _el13 = document.createElement('p');
  _el13.style.fontSize = '11.2px';
  _el13.style.fontWeight = '400';
  _el13.style.lineHeight = '1.5';
  _el13.style.color = '#64748b';
  const _t7 = document.createTextNode('');
  _t7.data = String("No tasks match the current filter.");
  _el13.appendChild(_t7);
  _el12.appendChild(_el13);
  _root.appendChild(_el12);

  container.appendChild(_root);
  return () => _root.remove();
}

export function mountTaskForm(container) {
  // @state
  const title = createSignal("");
  const assignee = createSignal("");
  const priority = createSignal("medium");
  const status = createSignal("todo");
  const dueDate = createSignal(null);
  const notes = createSignal("");
  const urgent = createSignal(false);
  const submitted = createSignal(false);
  const error = createSignal("");
  const touched = createSignal(false);

  // @computed
  const titleError = computed(() => (title() == "" ? "Title is required" : ""), [title]);
  const assigneeError = computed(() => (assignee() == "" ? "Assignee is required" : ""), [assignee]);
  const hasTitleError = computed(() => touched() && titleError() != "", [touched, titleError]);
  const hasAssigneeError = computed(() => touched() && assigneeError() != "", [touched, assigneeError]);
  const isValid = computed(() => titleError() == "" && assigneeError() == "", [titleError, assigneeError]);
  const hasError = computed(() => error() != "", [error]);
  const formSummary = computed(() => `Creating task: ${title()}`, [title]);
  const successVisible = computed(() => submitted(), [submitted]);

  // @actions
  function setTitle(v) {
    title.set(v);
    touched.set(true);
  }
  function setAssignee(v) {
    assignee.set(v);
    touched.set(true);
  }
  function setPriority(v) {
    priority.set(v);
  }
  function setStatus(v) {
    status.set(v);
  }
  function setDueDate(v) {
    dueDate.set(v);
  }
  function setNotes(v) {
    notes.set(v);
  }
  function setUrgent(v) {
    urgent.set(v);
  }
  function setError(e) {
    error.set(e);
  }
  function submitForm() {
    touched.set(true);
    if (isValid()) {
    fetch("http://localhost:4000/api/tasks", { method: "POST", body: JSON.stringify({ title: title(), assignee: assignee(), priority: priority(), status: status() }) });
    submitted.set(true);
    error.set("");
  }
  }
  function dismissSuccess() {
    submitted.set(false);
  }

  // DOM
  const _root = document.createElement('form');
  _root.setAttribute('novalidate', '');
  _root.addEventListener('submit', (e) => e.preventDefault());
  _root.style.color = '#202732';
  _root.style.fontFamily = "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif";
  _root.style.display = 'flex';
  _root.style.flexDirection = 'column';
  _root.style.gap = '20px';
  const _el0 = document.createElement('h2');
  _el0.style.fontSize = '34.2px';
  _el0.style.fontWeight = '700';
  _el0.style.lineHeight = '1.2';
  const _t0 = document.createTextNode('');
  _t0.data = String("Create New Task");
  _el0.appendChild(_t0);
  _root.appendChild(_el0);
  const _el1 = document.createElement('div');
  _el1.style.padding = '12px';
  _el1.style.backgroundColor = '#ecfdf5';
  _el1.style.border = '1px solid #bbf7d0';
  _el1.style.borderRadius = '8px';
  _el1.style.display = 'flex';
  _el1.style.flexDirection = 'row';
  _el1.style.gap = '12px';
  _el1.style.alignItems = 'center';
  bindVisibility(_el1, successVisible);
  mountIcon(_el1, { name: "check", size: "20px", color: "#10b981" });
  const _el2 = document.createElement('p');
  _el2.style.fontSize = '14px';
  _el2.style.fontWeight = '400';
  _el2.style.lineHeight = '1.5';
  _el2.style.color = '#10b981';
  const _t1 = document.createTextNode('');
  _t1.data = String("Task created successfully!");
  _el2.appendChild(_t1);
  _el1.appendChild(_el2);
  mountButton(_el1, { onClick: () => { dismissSuccess(); }, label: "Dismiss", variant: "ghost" });
  _root.appendChild(_el1);
  const _el3 = document.createElement('div');
  _el3.style.display = 'flex';
  _el3.style.flexDirection = 'column';
  _el3.style.gap = '16px';
  const _el4 = document.createElement('p');
  _el4.style.fontSize = '11.2px';
  _el4.style.fontWeight = '400';
  _el4.style.lineHeight = '1.5';
  const _t2 = document.createTextNode('');
  bindText(_t2, formSummary);
  _el4.appendChild(_t2);
  _el3.appendChild(_el4);
  const _el5 = document.createElement('div');
  _el5.style.display = 'flex';
  _el5.style.flexDirection = 'column';
  _el5.style.gap = '4px';
  const _hInput0 = mountInput(_el5, { onChange: (v) => { title.set(v); }, type: "text", label: "Title", value: title(), placeholder: "Enter task title", error: hasTitleError() });
  subscribe(title, (v) => { scheduleWrite(() => _hInput0.update({ value: v })); });
  subscribe(hasTitleError, (v) => { scheduleWrite(() => _hInput0.update({ error: v })); });
  const _el6 = document.createElement('div');
  bindVisibility(_el6, hasTitleError);
  const _el7 = document.createElement('p');
  _el7.style.fontSize = '11.2px';
  _el7.style.fontWeight = '400';
  _el7.style.lineHeight = '1.5';
  _el7.style.color = 'red';
  const _t3 = document.createTextNode('');
  bindText(_t3, titleError);
  _el7.appendChild(_t3);
  _el6.appendChild(_el7);
  _el5.appendChild(_el6);
  _el3.appendChild(_el5);
  const _hInput1 = mountInput(_el3, { onChange: (v) => { notes.set(v); }, type: "textarea", label: "Notes", value: notes(), placeholder: "Optional notes..." });
  subscribe(notes, (v) => { scheduleWrite(() => _hInput1.update({ value: v })); });
  const _el8 = document.createElement('div');
  _el8.style.display = 'flex';
  _el8.style.flexDirection = 'row';
  _el8.style.gap = '16px';
  const _el9 = document.createElement('div');
  _el9.style.display = 'flex';
  _el9.style.flexDirection = 'column';
  _el9.style.gap = '4px';
  const _hSelect2 = mountSelect(_el9, { onChange: (v) => { assignee.set(v); }, options: [{ value: "alice", label: "Alice" }, { value: "bob", label: "Bob" }, { value: "carol", label: "Carol" }], value: assignee(), placeholder: "Select assignee", label: "Assignee", error: hasAssigneeError() });
  subscribe(assignee, (v) => { scheduleWrite(() => _hSelect2.update({ value: v })); });
  subscribe(hasAssigneeError, (v) => { scheduleWrite(() => _hSelect2.update({ error: v })); });
  const _el10 = document.createElement('div');
  bindVisibility(_el10, hasAssigneeError);
  const _el11 = document.createElement('p');
  _el11.style.fontSize = '11.2px';
  _el11.style.fontWeight = '400';
  _el11.style.lineHeight = '1.5';
  _el11.style.color = 'red';
  const _t4 = document.createTextNode('');
  bindText(_t4, assigneeError);
  _el11.appendChild(_t4);
  _el10.appendChild(_el11);
  _el9.appendChild(_el10);
  _el8.appendChild(_el9);
  const _hSelect3 = mountSelect(_el8, { onChange: (v) => { priority.set(v); }, options: [{ value: "low", label: "Low" }, { value: "medium", label: "Medium" }, { value: "high", label: "High" }, { value: "critical", label: "Critical" }], value: priority(), label: "Priority" });
  subscribe(priority, (v) => { scheduleWrite(() => _hSelect3.update({ value: v })); });
  _el3.appendChild(_el8);
  const _el12 = document.createElement('div');
  _el12.style.display = 'flex';
  _el12.style.flexDirection = 'row';
  _el12.style.gap = '16px';
  const _hSelect4 = mountSelect(_el12, { onChange: (v) => { status.set(v); }, options: [{ value: "todo", label: "Todo" }, { value: "in-progress", label: "In Progress" }, { value: "done", label: "Done" }], value: status(), label: "Status" });
  subscribe(status, (v) => { scheduleWrite(() => _hSelect4.update({ value: v })); });
  const _hDatePicker5 = mountDatePicker(_el12, { onChange: (v) => { dueDate.set(v); }, value: dueDate(), label: "Due Date", placeholder: "Pick a date" });
  subscribe(dueDate, (v) => { scheduleWrite(() => _hDatePicker5.update({ value: v })); });
  _el3.appendChild(_el12);
  const _hCheckbox6 = mountCheckbox(_el3, { onChange: (v) => { urgent.set(v); }, label: "Mark as urgent", checked: urgent() });
  subscribe(urgent, (v) => { scheduleWrite(() => _hCheckbox6.update({ checked: v })); });
  const _el13 = document.createElement('div');
  _el13.style.padding = '12px';
  _el13.style.backgroundColor = '#fef2f2';
  _el13.style.border = '1px solid #fecaca';
  _el13.style.borderRadius = '8px';
  bindVisibility(_el13, hasError);
  const _el14 = document.createElement('p');
  _el14.style.fontSize = '11.2px';
  _el14.style.fontWeight = '400';
  _el14.style.lineHeight = '1.5';
  _el14.style.color = 'red';
  const _t5 = document.createTextNode('');
  bindText(_t5, error);
  _el14.appendChild(_t5);
  _el13.appendChild(_el14);
  _el3.appendChild(_el13);
  const _el15 = document.createElement('div');
  _el15.style.display = 'flex';
  _el15.style.flexDirection = 'row';
  _el15.style.gap = '12px';
  mountButton(_el15, { onClick: () => { submitForm(); }, label: "Create Task", variant: "primary" });
  _el3.appendChild(_el15);
  _root.appendChild(_el3);

  container.appendChild(_root);
  return () => _root.remove();
}

export function mountTaskDetail(container) {
  // @state
  const task = createSignal(null);

  // @computed
  const hasTask = computed(() => task() != null, [task]);
  const taskTitle = computed(() => (task() != null ? task().title : ""), [task]);
  const taskStatus = computed(() => (task() != null ? task().status : ""), [task]);
  const taskAssignee = computed(() => (task() != null ? task().assignee : ""), [task]);
  const taskPriority = computed(() => (task() != null ? task().priority : ""), [task]);
  const taskDate = computed(() => (task() != null ? task().createdAt : ""), [task]);
  const detailHeading = computed(() => `Task: ${taskTitle()}`, [taskTitle]);

  // @actions
  function setTask(t) {
    task.set(t);
  }

  // DOM
  const _root = document.createElement('div');
  _root.style.color = '#202732';
  _root.style.fontFamily = "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif";
  _root.style.display = 'flex';
  _root.style.flexDirection = 'column';
  _root.style.gap = '16px';
  const _el0 = document.createElement('h2');
  _el0.style.fontSize = '34.2px';
  _el0.style.fontWeight = '700';
  _el0.style.lineHeight = '1.2';
  const _t0 = document.createTextNode('');
  _t0.data = String("Task Detail");
  _el0.appendChild(_t0);
  _root.appendChild(_el0);
  const _el1 = document.createElement('div');
  _el1.style.padding = '16px';
  _el1.style.backgroundColor = '#f8fafc';
  _el1.style.borderRadius = '8px';
  _el1.style.display = 'flex';
  _el1.style.flexDirection = 'column';
  _el1.style.gap = '8px';
  _el1.style.alignItems = 'center';
  const _sig0 = computed(() => Boolean(!hasTask()), [hasTask]);
  bindVisibility(_el1, _sig0);
  mountIcon(_el1, { name: "info", size: "24px", color: "#94a3b8" });
  const _el2 = document.createElement('p');
  _el2.style.fontSize = '11.2px';
  _el2.style.fontWeight = '400';
  _el2.style.lineHeight = '1.5';
  _el2.style.color = '#64748b';
  const _t1 = document.createTextNode('');
  _t1.data = String("Select a task to view details.");
  _el2.appendChild(_t1);
  _el1.appendChild(_el2);
  _root.appendChild(_el1);
  const _el3 = document.createElement('div');
  _el3.style.display = 'flex';
  _el3.style.flexDirection = 'column';
  _el3.style.gap = '16px';
  bindVisibility(_el3, hasTask);
  const _el4 = document.createElement('h3');
  _el4.style.fontSize = '27.3px';
  _el4.style.fontWeight = '600';
  _el4.style.lineHeight = '1.2';
  const _t2 = document.createTextNode('');
  bindText(_t2, detailHeading);
  _el4.appendChild(_t2);
  _el3.appendChild(_el4);
  mountImage(_el3, { src: "https://via.placeholder.com/64", alt: "Task icon", width: 64, height: 64 });
  const _el5 = document.createElement('div');
  _el5.style.display = 'flex';
  _el5.style.flexDirection = 'row';
  _el5.style.gap = '16px';
  const _el6 = document.createElement('div');
  _el6.style.padding = '12px';
  _el6.style.backgroundColor = '#f8fafc';
  _el6.style.borderRadius = '8px';
  _el6.style.display = 'flex';
  _el6.style.flexDirection = 'column';
  _el6.style.gap = '4px';
  const _el7 = document.createElement('span');
  _el7.style.fontSize = '11.2px';
  _el7.style.fontWeight = '500';
  _el7.style.lineHeight = '1.4';
  _el7.style.color = '#64748b';
  const _t3 = document.createTextNode('');
  _t3.data = String("Status");
  _el7.appendChild(_t3);
  _el6.appendChild(_el7);
  mountStatusBadge(_el6, taskStatus());
  _el5.appendChild(_el6);
  const _el8 = document.createElement('div');
  _el8.style.padding = '12px';
  _el8.style.backgroundColor = '#f8fafc';
  _el8.style.borderRadius = '8px';
  _el8.style.display = 'flex';
  _el8.style.flexDirection = 'column';
  _el8.style.gap = '4px';
  const _el9 = document.createElement('span');
  _el9.style.fontSize = '11.2px';
  _el9.style.fontWeight = '500';
  _el9.style.lineHeight = '1.4';
  _el9.style.color = '#64748b';
  const _t4 = document.createTextNode('');
  _t4.data = String("Priority");
  _el9.appendChild(_t4);
  _el8.appendChild(_el9);
  mountPriorityBadge(_el8, taskPriority());
  _el5.appendChild(_el8);
  const _el10 = document.createElement('div');
  _el10.style.padding = '12px';
  _el10.style.backgroundColor = '#f8fafc';
  _el10.style.borderRadius = '8px';
  _el10.style.display = 'flex';
  _el10.style.flexDirection = 'column';
  _el10.style.gap = '4px';
  const _el11 = document.createElement('span');
  _el11.style.fontSize = '11.2px';
  _el11.style.fontWeight = '500';
  _el11.style.lineHeight = '1.4';
  _el11.style.color = '#64748b';
  const _t5 = document.createTextNode('');
  _t5.data = String("Assignee");
  _el11.appendChild(_t5);
  _el10.appendChild(_el11);
  const _el12 = document.createElement('p');
  _el12.style.fontSize = '14px';
  _el12.style.fontWeight = '400';
  _el12.style.lineHeight = '1.5';
  const _t6 = document.createTextNode('');
  bindText(_t6, taskAssignee);
  _el12.appendChild(_t6);
  _el10.appendChild(_el12);
  _el5.appendChild(_el10);
  const _el13 = document.createElement('div');
  _el13.style.padding = '12px';
  _el13.style.backgroundColor = '#f8fafc';
  _el13.style.borderRadius = '8px';
  _el13.style.display = 'flex';
  _el13.style.flexDirection = 'column';
  _el13.style.gap = '4px';
  const _el14 = document.createElement('span');
  _el14.style.fontSize = '11.2px';
  _el14.style.fontWeight = '500';
  _el14.style.lineHeight = '1.4';
  _el14.style.color = '#64748b';
  const _t7 = document.createTextNode('');
  _t7.data = String("Created");
  _el14.appendChild(_t7);
  _el13.appendChild(_el14);
  const _el15 = document.createElement('p');
  _el15.style.fontSize = '14px';
  _el15.style.fontWeight = '400';
  _el15.style.lineHeight = '1.5';
  const _t8 = document.createTextNode('');
  bindText(_t8, taskDate);
  _el15.appendChild(_t8);
  _el13.appendChild(_el15);
  _el5.appendChild(_el13);
  _el3.appendChild(_el5);
  mountButton(_el3, { onClick: () => { setTask(null); }, label: "Back", variant: "secondary" });
  _root.appendChild(_el3);

  container.appendChild(_root);
  return () => _root.remove();
}

export function mountWizardStep1(container) {
  // @state
  const title = createSignal("");
  const assignee = createSignal("");

  // @computed
  const titleFilled = computed(() => title() != "", [title]);

  // @actions
  function setTitle(v) {
    title.set(v);
  }
  function setAssignee(v) {
    assignee.set(v);
  }

  // DOM
  const _root = document.createElement('form');
  _root.setAttribute('novalidate', '');
  _root.addEventListener('submit', (e) => e.preventDefault());
  _root.style.color = '#202732';
  _root.style.fontFamily = "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif";
  _root.style.display = 'flex';
  _root.style.flexDirection = 'column';
  _root.style.gap = '20px';
  const _el0 = document.createElement('h3');
  _el0.style.fontSize = '27.3px';
  _el0.style.fontWeight = '600';
  _el0.style.lineHeight = '1.2';
  const _t0 = document.createTextNode('');
  _t0.data = String("Step 1: Basic Info");
  _el0.appendChild(_t0);
  _root.appendChild(_el0);
  const _el1 = document.createElement('p');
  _el1.style.fontSize = '11.2px';
  _el1.style.fontWeight = '400';
  _el1.style.lineHeight = '1.5';
  const _t1 = document.createTextNode('');
  _t1.data = String("Provide the core details for this task.");
  _el1.appendChild(_t1);
  _root.appendChild(_el1);
  const _hInput0 = mountInput(_root, { onChange: (v) => { title.set(v); }, type: "text", label: "Title", value: title(), placeholder: "Task title" });
  subscribe(title, (v) => { scheduleWrite(() => _hInput0.update({ value: v })); });
  const _hSelect1 = mountSelect(_root, { onChange: (v) => { assignee.set(v); }, options: [{ value: "alice", label: "Alice" }, { value: "bob", label: "Bob" }, { value: "carol", label: "Carol" }], value: assignee(), placeholder: "Choose assignee", label: "Assignee" });
  subscribe(assignee, (v) => { scheduleWrite(() => _hSelect1.update({ value: v })); });
  const _el2 = document.createElement('div');
  _el2.style.display = 'flex';
  _el2.style.flexDirection = 'row';
  _el2.style.gap = '12px';
  _el2.style.justifyContent = 'flex-end';
  mountButton(_el2, { label: "Next", variant: "primary" });
  _root.appendChild(_el2);

  container.appendChild(_root);
  return () => _root.remove();
}

export function mountWizardStep2(container) {
  // @state
  const priority = createSignal("medium");
  const dueDate = createSignal(null);
  const autoAssign = createSignal(false);

  // @actions
  function setPriority(v) {
    priority.set(v);
  }
  function setDueDate(v) {
    dueDate.set(v);
  }
  function setAutoAssign(v) {
    autoAssign.set(v);
  }

  // DOM
  const _root = document.createElement('form');
  _root.setAttribute('novalidate', '');
  _root.addEventListener('submit', (e) => e.preventDefault());
  _root.style.color = '#202732';
  _root.style.fontFamily = "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif";
  _root.style.display = 'flex';
  _root.style.flexDirection = 'column';
  _root.style.gap = '20px';
  const _el0 = document.createElement('h3');
  _el0.style.fontSize = '27.3px';
  _el0.style.fontWeight = '600';
  _el0.style.lineHeight = '1.2';
  const _t0 = document.createTextNode('');
  _t0.data = String("Step 2: Options");
  _el0.appendChild(_t0);
  _root.appendChild(_el0);
  const _el1 = document.createElement('p');
  _el1.style.fontSize = '11.2px';
  _el1.style.fontWeight = '400';
  _el1.style.lineHeight = '1.5';
  const _t1 = document.createTextNode('');
  _t1.data = String("Configure priority, deadline, and assignment options.");
  _el1.appendChild(_t1);
  _root.appendChild(_el1);
  const _hSelect0 = mountSelect(_root, { onChange: (v) => { priority.set(v); }, options: [{ value: "low", label: "Low" }, { value: "medium", label: "Medium" }, { value: "high", label: "High" }, { value: "critical", label: "Critical" }], value: priority(), label: "Priority" });
  subscribe(priority, (v) => { scheduleWrite(() => _hSelect0.update({ value: v })); });
  const _hDatePicker1 = mountDatePicker(_root, { onChange: (v) => { dueDate.set(v); }, value: dueDate(), label: "Due Date", placeholder: "Select deadline" });
  subscribe(dueDate, (v) => { scheduleWrite(() => _hDatePicker1.update({ value: v })); });
  const _hToggle2 = mountToggle(_root, { onChange: (v) => { autoAssign.set(v); }, checked: autoAssign(), label: "Auto-assign reviewer" });
  subscribe(autoAssign, (v) => { scheduleWrite(() => _hToggle2.update({ checked: v })); });
  const _el2 = document.createElement('div');
  _el2.style.display = 'flex';
  _el2.style.flexDirection = 'row';
  _el2.style.gap = '12px';
  _el2.style.justifyContent = 'flex-end';
  mountButton(_el2, { label: "Back", variant: "ghost" });
  mountButton(_el2, { label: "Next", variant: "primary" });
  _root.appendChild(_el2);

  container.appendChild(_root);
  return () => _root.remove();
}

export function mountWizardStep3(container) {
  // @state
  const confirmed = createSignal(false);

  // @actions
  function setConfirmed(v) {
    confirmed.set(v);
  }

  // DOM
  const _root = document.createElement('form');
  _root.setAttribute('novalidate', '');
  _root.addEventListener('submit', (e) => e.preventDefault());
  _root.style.color = '#202732';
  _root.style.fontFamily = "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif";
  _root.style.display = 'flex';
  _root.style.flexDirection = 'column';
  _root.style.gap = '20px';
  const _el0 = document.createElement('h3');
  _el0.style.fontSize = '27.3px';
  _el0.style.fontWeight = '600';
  _el0.style.lineHeight = '1.2';
  const _t0 = document.createTextNode('');
  _t0.data = String("Step 3: Review & Confirm");
  _el0.appendChild(_t0);
  _root.appendChild(_el0);
  const _el1 = document.createElement('p');
  _el1.style.fontSize = '11.2px';
  _el1.style.fontWeight = '400';
  _el1.style.lineHeight = '1.5';
  const _t1 = document.createTextNode('');
  _t1.data = String("Please review your task details and confirm submission.");
  _el1.appendChild(_t1);
  _root.appendChild(_el1);
  const _el2 = document.createElement('div');
  _el2.style.display = 'flex';
  _el2.style.flexDirection = 'row';
  _el2.style.gap = '8px';
  _el2.style.alignItems = 'center';
  mountIcon(_el2, { name: "info", size: "18px", color: "#6366f1" });
  const _el3 = document.createElement('p');
  _el3.style.fontSize = '11.2px';
  _el3.style.fontWeight = '400';
  _el3.style.lineHeight = '1.5';
  const _t2 = document.createTextNode('');
  _t2.data = String("All fields can be edited later.");
  _el3.appendChild(_t2);
  _el2.appendChild(_el3);
  _root.appendChild(_el2);
  const _hCheckbox0 = mountCheckbox(_root, { onChange: (v) => { confirmed.set(v); }, label: "I confirm this task is correct", checked: confirmed() });
  subscribe(confirmed, (v) => { scheduleWrite(() => _hCheckbox0.update({ checked: v })); });
  const _el4 = document.createElement('div');
  _el4.style.display = 'flex';
  _el4.style.flexDirection = 'row';
  _el4.style.gap = '12px';
  _el4.style.justifyContent = 'flex-end';
  mountButton(_el4, { label: "Back", variant: "ghost" });
  const _hButton1 = mountButton(_el4, { label: "Submit", variant: "primary", disabled: !confirmed() });
  const _cpdisabled2 = computed(() => !confirmed(), [confirmed]);
  subscribe(_cpdisabled2, (v) => { scheduleWrite(() => _hButton1.update({ disabled: v })); });
  _root.appendChild(_el4);

  container.appendChild(_root);
  return () => _root.remove();
}

export function mountApp(container) {
  // @state
  const theme = createSignal("light");
  const view = createSignal("dashboard");

  // @source
  const _src_stats = createStatsAPI();
  const stats = _src_stats.data;
  const statsLoading = _src_stats.loading;
  const statsError = _src_stats.error;
  _src_stats.fetch();

  // @computed
  const themeLabel = computed(() => (theme() == "light" ? "Dark Mode" : "Light Mode"), [theme]);
  const showDashboard = computed(() => view() == "dashboard", [view]);
  const showDetail = computed(() => view() == "detail", [view]);
  const showCreate = computed(() => view() == "create", [view]);
  const showWizard = computed(() => view() == "wizard", [view]);
  const viewTitle = computed(() => (view() === "dashboard" ? "Dashboard" : (view() === "detail" ? "Task Detail" : (view() === "create" ? "Create Task" : (view() === "wizard" ? "Task Wizard" : "Admin")))), [view]);
  const statsTotal = computed(() => (stats() != null ? stats().total : 0), [stats]);
  const statsDone = computed(() => (stats() != null ? stats().done : 0), [stats]);
  const statsInProgress = computed(() => (stats() != null ? stats().inProgress : 0), [stats]);
  const statsTodo = computed(() => (stats() != null ? stats().todo : 0), [stats]);

  // @actions
  function toggleTheme() {
    theme.set((theme() == "light" ? "dark" : "light"));
  }
  function setView(v) {
    view.set(v);
  }

  // DOM
  const _root = document.createElement('form');
  _root.setAttribute('novalidate', '');
  _root.addEventListener('submit', (e) => e.preventDefault());
  _root.setAttribute('role', 'main');
  _root.id = 'spec-main-content';
  const _skip = document.createElement('a');
  _skip.href = '#spec-main-content';
  _skip.className = 'spec-skip-link';
  _skip.textContent = 'Skip to main content';
  _skip.style.cssText = 'position:absolute;left:-9999px;top:auto;width:1px;height:1px;overflow:hidden;z-index:10000';
  _skip.addEventListener('focus', () => { _skip.style.cssText = 'position:absolute;left:8px;top:8px;z-index:10000;padding:8px 16px;background:#fff;border:2px solid #6366f1;border-radius:4px;font-size:14px;color:#202732'; });
  _skip.addEventListener('blur', () => { _skip.style.cssText = 'position:absolute;left:-9999px;top:auto;width:1px;height:1px;overflow:hidden;z-index:10000'; });
  _root.prepend(_skip);
  const _rootColor = computed(() => theme() === 'dark' ? '#eeeff1' : '#202732', [theme]);
  bindStyle(_root, 'color', _rootColor);
  _root.style.fontFamily = "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif";
  _root.style.display = 'flex';
  _root.style.flexDirection = 'column';
  _root.style.gap = '24px';
  const _el0 = document.createElement('div');
  _el0.style.padding = '16px';
  _el0.style.backgroundColor = '#ffffff';
  _el0.style.border = '1px solid #e2e8f0';
  _el0.style.borderRadius = '12px';
  _el0.style.display = 'flex';
  _el0.style.flexDirection = 'row';
  _el0.style.gap = '16px';
  _el0.style.alignItems = 'center';
  _el0.style.justifyContent = 'space-between';
  const _el1 = document.createElement('div');
  _el1.style.display = 'flex';
  _el1.style.flexDirection = 'row';
  _el1.style.gap = '12px';
  _el1.style.alignItems = 'center';
  mountIcon(_el1, { name: "home", size: "22px", color: "#6366f1" });
  const _el2 = document.createElement('h2');
  _el2.style.fontSize = '34.2px';
  _el2.style.fontWeight = '700';
  _el2.style.lineHeight = '1.2';
  const _t0 = document.createTextNode('');
  bindText(_t0, viewTitle);
  _el2.appendChild(_t0);
  _el1.appendChild(_el2);
  _el0.appendChild(_el1);
  const _el3 = document.createElement('div');
  _el3.style.display = 'flex';
  _el3.style.flexDirection = 'row';
  _el3.style.gap = '12px';
  _el3.style.alignItems = 'center';
  const _hToggle0 = mountToggle(_el3, { onChange: () => { toggleTheme(); }, checked: theme() == "dark", label: themeLabel() });
  const _cpchecked1 = computed(() => theme() == "dark", [theme]);
  subscribe(_cpchecked1, (v) => { scheduleWrite(() => _hToggle0.update({ checked: v })); });
  subscribe(themeLabel, (v) => { scheduleWrite(() => _hToggle0.update({ label: v })); });
  _el0.appendChild(_el3);
  _root.appendChild(_el0);
  const _hTabs2 = mountTabs(_root, { onChange: (v) => { view.set(v); }, tabs: [{ id: "dashboard", label: "Dashboard" }, { id: "detail", label: "Detail" }, { id: "create", label: "New Task" }, { id: "wizard", label: "Wizard" }], activeTab: view() });
  subscribe(view, (v) => { scheduleWrite(() => _hTabs2.update({ activeTab: v })); });
  const _el4 = document.createElement('div');
  _el4.style.display = 'flex';
  _el4.style.flexDirection = 'column';
  _el4.style.gap = '24px';
  bindVisibility(_el4, showDashboard);
  const _el5 = document.createElement('div');
  const _cardBg3 = computed(() => theme() === 'dark' ? '#3b4e68' : '#ffffff', [theme]);
  bindStyle(_el5, 'backgroundColor', _cardBg3);
  const _cardBorder4 = computed(() => theme() === 'dark' ? '1px solid #3b4e68' : '1px solid #dce0e5', [theme]);
  bindStyle(_el5, 'border', _cardBorder4);
  _el5.style.padding = '16px';
  _el5.style.borderRadius = '8px';
  _el5.style.boxShadow = '0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.08)';
  mountStatsBar(_el5, statsTotal(), statsDone(), statsInProgress(), statsTodo());
  _el4.appendChild(_el5);
  const _el6 = document.createElement('div');
  const _cardBg5 = computed(() => theme() === 'dark' ? '#3b4e68' : '#ffffff', [theme]);
  bindStyle(_el6, 'backgroundColor', _cardBg5);
  const _cardBorder6 = computed(() => theme() === 'dark' ? '1px solid #3b4e68' : '1px solid #dce0e5', [theme]);
  bindStyle(_el6, 'border', _cardBorder6);
  _el6.style.padding = '16px';
  _el6.style.borderRadius = '8px';
  _el6.style.boxShadow = '0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.08)';
  mountTaskTable(_el6);
  _el4.appendChild(_el6);
  _root.appendChild(_el4);
  const _el7 = document.createElement('div');
  bindVisibility(_el7, showDetail);
  const _el8 = document.createElement('div');
  const _cardBg7 = computed(() => theme() === 'dark' ? '#3b4e68' : '#ffffff', [theme]);
  bindStyle(_el8, 'backgroundColor', _cardBg7);
  const _cardBorder8 = computed(() => theme() === 'dark' ? '1px solid #3b4e68' : '1px solid #dce0e5', [theme]);
  bindStyle(_el8, 'border', _cardBorder8);
  _el8.style.padding = '16px';
  _el8.style.borderRadius = '8px';
  _el8.style.boxShadow = '0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.08)';
  mountTaskDetail(_el8);
  _el7.appendChild(_el8);
  _root.appendChild(_el7);
  const _el9 = document.createElement('div');
  bindVisibility(_el9, showCreate);
  const _el10 = document.createElement('div');
  const _cardBg9 = computed(() => theme() === 'dark' ? '#3b4e68' : '#ffffff', [theme]);
  bindStyle(_el10, 'backgroundColor', _cardBg9);
  const _cardBorder10 = computed(() => theme() === 'dark' ? '1px solid #3b4e68' : '1px solid #dce0e5', [theme]);
  bindStyle(_el10, 'border', _cardBorder10);
  _el10.style.padding = '16px';
  _el10.style.borderRadius = '8px';
  _el10.style.boxShadow = '0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.08)';
  mountTaskForm(_el10);
  _el9.appendChild(_el10);
  _root.appendChild(_el9);
  const _el11 = document.createElement('div');
  bindVisibility(_el11, showWizard);
  const _el12 = document.createElement('div');
  const _cardBg11 = computed(() => theme() === 'dark' ? '#3b4e68' : '#ffffff', [theme]);
  bindStyle(_el12, 'backgroundColor', _cardBg11);
  const _cardBorder12 = computed(() => theme() === 'dark' ? '1px solid #3b4e68' : '1px solid #dce0e5', [theme]);
  bindStyle(_el12, 'border', _cardBorder12);
  _el12.style.padding = '16px';
  _el12.style.borderRadius = '8px';
  _el12.style.boxShadow = '0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.08)';
  mountTaskWizard(_el12);
  _el11.appendChild(_el12);
  _root.appendChild(_el11);

  container.appendChild(_root);
  return () => _root.remove();
}


export function mountTaskWizard(container, options = {}) {
  let _state = 'Info';
  let _cleanup = null;
  let _surfaceEl = null;

  const _panel = document.createElement('div');
  _panel.className = 'spec-flow spec-flow--TaskWizard';

  function _render(state, data) {
    if (_cleanup) { _cleanup(); _cleanup = null; }
    const _el = document.createElement('div');
    _el.className = 'spec-flow-state spec-flow-state--' + state;
    switch (state) {
      case 'Info':
        if (typeof mountWizardStep1 === 'function') _cleanup = mountWizardStep1(_el, { dispatch, data });
        break;
      case 'Options':
        if (typeof mountWizardStep2 === 'function') _cleanup = mountWizardStep2(_el, { dispatch, data });
        break;
      case 'Review':
        if (typeof mountWizardStep3 === 'function') _cleanup = mountWizardStep3(_el, { dispatch, data });
        break;
      case 'Done':
        if (typeof mountWizardStep3 === 'function') _cleanup = mountWizardStep3(_el, { dispatch, data });
        break;
    }
    if (_surfaceEl) {
      _panel.replaceChild(_el, _surfaceEl);
    } else {
      _panel.appendChild(_el);
    }
    _surfaceEl = _el;
  }

  function _go(newState, data, skipHistory) {
    _state = newState;
    _render(newState, data);
    if (!skipHistory && options.history !== false) {
      history.pushState({ flowState: newState }, '', '#' + newState);
    }
  }

  function dispatch(event, arg) {
    switch (_state) {
      case 'Info': {
        if (event === 'next') {
          if (!(title != "")) return;
          _go('Options', null);
        }
        break;
      }
      case 'Options': {
        if (event === 'back') {
          _go('Info', null);
        }
        else if (event === 'next') {
          _go('Review', null);
        }
        break;
      }
      case 'Review': {
        if (event === 'back') {
          _go('Options', null);
        }
        else if (event === 'submit') {
          if (!(confirmed)) return;
          _go('Done', null);
        }
        break;
      }
      case 'Done': {
        if (event === 'restart') {
          _go('Info', null);
        }
        break;
      }
    }
  }

  const _onPopState = (e) => {
    const s = (e.state && e.state.flowState) || 'Info';
    _state = s;
    _render(s, null);
  };

  if (options.history !== false) {
    window.addEventListener('popstate', _onPopState);
    history.replaceState({ flowState: 'Info' }, '', '#Info');
  }

  container.appendChild(_panel);
  _render('Info', null);

  return () => {
    if (options.history !== false) window.removeEventListener('popstate', _onPopState);
    if (_cleanup) _cleanup();
    _panel.remove();
  };
}


export function createTasksAPI(params = {}) {
  return createSource({
    endpoint: 'http://localhost:4000/api/tasks',
    method: 'GET',
    cacheTtl: 60000,
    retryAttempts: 3,
    retryStrategy: 'exponential',
    ...params,
  });
}

export function createStatsAPI(params = {}) {
  return createSource({
    endpoint: 'http://localhost:4000/api/stats',
    method: 'GET',
    cacheTtl: 60000,
    ...params,
  });
}

export function createUsersAPI(params = {}) {
  return createSource({
    endpoint: 'http://localhost:4000/api/users',
    method: 'GET',
    cacheTtl: 300000,
    ...params,
  });
}
